version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.31
    container_name: jaeger
    ports:
      - "5775:5775/udp"   # jaeger-agent (zipkin-compact)
      - "6831:6831/udp"   # jaeger-agent (thrift-compact)
      - "6832:6832/udp"   # jaeger-agent (thrift-binary)
      - "5778:5778"       # jaeger-agent admin port
      - "16686:16686"     # jaeger-query
      - "14268:14268"     # jaeger-collector
      - "14250:14250"     # jaeger-grpc
      - "9411:9411"       # jaeger-collector (zipkin)
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

networks:
  jaeger_network:
    driver: bridge
