migrate-pg:
  dialect: postgres
  datasource: port=${DB_PORT} dbname=${DB_NAME} sslmode=disable user=${DB_USER} password=${DB_PASS} host=${DB_HOST}
  dir: ./db/pg/migration
  table: gorp_migration_{APP_NAME}

migrate-mysql:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true&tls=false
  dir: ./db/pg/migration
  table: gorp_migration_{APP_NAME}